name: Test

on: [push]

jobs:
  local-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: remote-action
        uses: ./.github/actions/my-action
        with:
          message: "Hola, imbecil!"