name: Ejemplo de composite action

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    env:
      MY_VAR: Mi variable de entorno

    steps:
      - name: Test
        env:
          STEP_MY_VAR: Mi variable de entorno 2
        run: echo "$STEP_MY_VAR"